import product1 from "../public/product.webp";

const productItems = [
  {
    id: 1,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 2,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 3,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 4,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 5,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 6,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 7,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 8,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 9,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 10,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 11,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 12,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 13,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 14,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 15,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 16,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 17,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 18,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 19,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
  {
    id: 20,
    image: product1,
    name: "Diamond Milk",
    price: 50000,
    category: "Dairy Products",
    description: "Fresh Milk",
    discountType: 1,
  },
];

export default productItems;
